from src.data_processing import image_transformation as it

simple_pipeline = [
    [it.Transformation.MIRROR, it.Transformation.ROTATE],
    [it.Transformation.MIRROR, it.Transformation.NOISE],
    [it.Transformation.MIRROR]
]

single_pipelines = [
    # SINGLES
    [it.Transformation.ROTATE],
    [it.Transformation.MIRROR],
    [it.Transformation.SUB],
    [it.Transformation.SHUFFLE],
    [it.Transformation.CIRCLES],
    [it.Transformation.INVERT],
    [it.Transformation.SHIFT_COLOR],
    [it.Transformation.NOISE]
]

full_pipelines = [
    # SINGLES
    [it.Transformation.ROTATE],
    [it.Transformation.MIRROR],
    [it.Transformation.SUB],
    [it.Transformation.SHUFFLE],
    [it.Transformation.CIRCLES],
    [it.Transformation.INVERT],
    [it.Transformation.SHIFT_COLOR],
    [it.Transformation.NOISE],
    
    # PAIRS
    [it.Transformation.ROTATE, it.Transformation.MIRROR],
    [it.Transformation.SUB, it.Transformation.ROTATE],
    [it.Transformation.SHUFFLE, it.Transformation.ROTATE],
    [it.Transformation.CIRCLES, it.Transformation.ROTATE],
    [it.Transformation.ROTATE, it.Transformation.INVERT],
    [it.Transformation.ROTATE, it.Transformation.SHIFT_COLOR],
    [it.Transformation.ROTATE, it.Transformation.NOISE],
    [it.Transformation.MIRROR, it.Transformation.SUB],
    [it.Transformation.MIRROR, it.Transformation.SHUFFLE],
    [it.Transformation.MIRROR, it.Transformation.CIRCLES],
    [it.Transformation.MIRROR, it.Transformation.INVERT],
    [it.Transformation.MIRROR, it.Transformation.SHIFT_COLOR],
    [it.Transformation.MIRROR, it.Transformation.NOISE],
    [it.Transformation.SUB, it.Transformation.SHUFFLE],
    [it.Transformation.SUB, it.Transformation.CIRCLES],
    [it.Transformation.SUB, it.Transformation.INVERT],
    [it.Transformation.SUB, it.Transformation.SHIFT_COLOR],
    [it.Transformation.SUB, it.Transformation.NOISE],
    [it.Transformation.SHUFFLE, it.Transformation.CIRCLES],
    [it.Transformation.SHUFFLE, it.Transformation.INVERT],
    [it.Transformation.SHUFFLE, it.Transformation.SHIFT_COLOR],
    [it.Transformation.SHUFFLE, it.Transformation.NOISE],
    [it.Transformation.CIRCLES, it.Transformation.INVERT],
    [it.Transformation.CIRCLES, it.Transformation.SHIFT_COLOR],
    [it.Transformation.CIRCLES, it.Transformation.NOISE],
    [it.Transformation.INVERT, it.Transformation.SHIFT_COLOR],
    [it.Transformation.INVERT, it.Transformation.NOISE],
    [it.Transformation.SHIFT_COLOR, it.Transformation.NOISE],
    
    # TRIOS
    [it.Transformation.SUB, it.Transformation.ROTATE, it.Transformation.MIRROR],
    [it.Transformation.SHUFFLE, it.Transformation.ROTATE, it.Transformation.MIRROR],
    [it.Transformation.CIRCLES, it.Transformation.ROTATE, it.Transformation.MIRROR],
    [it.Transformation.ROTATE, it.Transformation.MIRROR, it.Transformation.INVERT],
    [it.Transformation.ROTATE, it.Transformation.MIRROR, it.Transformation.SHIFT_COLOR],
    [it.Transformation.ROTATE, it.Transformation.MIRROR, it.Transformation.NOISE],
    [it.Transformation.SUB, it.Transformation.SHUFFLE, it.Transformation.ROTATE],
    [it.Transformation.SUB, it.Transformation.CIRCLES, it.Transformation.ROTATE],
    [it.Transformation.SUB, it.Transformation.INVERT, it.Transformation.ROTATE],
    [it.Transformation.SUB, it.Transformation.SHIFT_COLOR, it.Transformation.ROTATE],
    [it.Transformation.SUB, it.Transformation.NOISE, it.Transformation.ROTATE],
    [it.Transformation.SHUFFLE, it.Transformation.CIRCLES, it.Transformation.ROTATE],
    [it.Transformation.SHUFFLE, it.Transformation.INVERT, it.Transformation.ROTATE],
    [it.Transformation.SHUFFLE, it.Transformation.ROTATE, it.Transformation.SHIFT_COLOR],
    [it.Transformation.SHUFFLE, it.Transformation.ROTATE, it.Transformation.NOISE],
    [it.Transformation.ROTATE, it.Transformation.CIRCLES, it.Transformation.INVERT],
    [it.Transformation.ROTATE, it.Transformation.CIRCLES, it.Transformation.SHIFT_COLOR],
    [it.Transformation.ROTATE, it.Transformation.CIRCLES, it.Transformation.NOISE],
    [it.Transformation.INVERT, it.Transformation.ROTATE, it.Transformation.SHIFT_COLOR],
    [it.Transformation.INVERT, it.Transformation.ROTATE, it.Transformation.NOISE],
    [it.Transformation.ROTATE, it.Transformation.SHIFT_COLOR, it.Transformation.NOISE],
    [it.Transformation.MIRROR, it.Transformation.SUB, it.Transformation.SHUFFLE],
    [it.Transformation.MIRROR, it.Transformation.SUB, it.Transformation.CIRCLES],
    [it.Transformation.MIRROR, it.Transformation.SUB, it.Transformation.INVERT],
    [it.Transformation.MIRROR, it.Transformation.SUB, it.Transformation.SHIFT_COLOR],
    [it.Transformation.MIRROR, it.Transformation.SUB, it.Transformation.NOISE],
    [it.Transformation.MIRROR, it.Transformation.SHUFFLE, it.Transformation.CIRCLES],
    [it.Transformation.MIRROR, it.Transformation.SHUFFLE, it.Transformation.INVERT],
    [it.Transformation.MIRROR, it.Transformation.SHUFFLE, it.Transformation.SHIFT_COLOR],
    [it.Transformation.MIRROR, it.Transformation.SHUFFLE, it.Transformation.NOISE],
    [it.Transformation.MIRROR, it.Transformation.CIRCLES, it.Transformation.INVERT],
    [it.Transformation.MIRROR, it.Transformation.CIRCLES, it.Transformation.SHIFT_COLOR],
    [it.Transformation.MIRROR, it.Transformation.CIRCLES, it.Transformation.NOISE],
    [it.Transformation.MIRROR, it.Transformation.INVERT, it.Transformation.SHIFT_COLOR],
    [it.Transformation.MIRROR, it.Transformation.INVERT, it.Transformation.NOISE],
    [it.Transformation.MIRROR, it.Transformation.SHIFT_COLOR, it.Transformation.NOISE],
    [it.Transformation.SUB, it.Transformation.SHUFFLE, it.Transformation.CIRCLES],
    [it.Transformation.SUB, it.Transformation.SHUFFLE, it.Transformation.INVERT],
    [it.Transformation.SUB, it.Transformation.SHUFFLE, it.Transformation.SHIFT_COLOR],
    [it.Transformation.SUB, it.Transformation.SHUFFLE, it.Transformation.NOISE],
    [it.Transformation.SUB, it.Transformation.CIRCLES, it.Transformation.INVERT],
    [it.Transformation.SUB, it.Transformation.CIRCLES, it.Transformation.SHIFT_COLOR],
    [it.Transformation.SUB, it.Transformation.CIRCLES, it.Transformation.NOISE],
    [it.Transformation.SUB, it.Transformation.INVERT, it.Transformation.SHIFT_COLOR],
    [it.Transformation.SUB, it.Transformation.INVERT, it.Transformation.NOISE],
    [it.Transformation.SUB, it.Transformation.SHIFT_COLOR, it.Transformation.NOISE],
    [it.Transformation.SHUFFLE, it.Transformation.CIRCLES, it.Transformation.INVERT],
    [it.Transformation.SHUFFLE, it.Transformation.CIRCLES, it.Transformation.SHIFT_COLOR],
    [it.Transformation.SHUFFLE, it.Transformation.CIRCLES, it.Transformation.NOISE],
    [it.Transformation.SHUFFLE, it.Transformation.INVERT, it.Transformation.SHIFT_COLOR],
    [it.Transformation.SHUFFLE, it.Transformation.INVERT, it.Transformation.NOISE],
    [it.Transformation.SHUFFLE, it.Transformation.SHIFT_COLOR, it.Transformation.NOISE],
    [it.Transformation.CIRCLES, it.Transformation.INVERT, it.Transformation.SHIFT_COLOR],
    [it.Transformation.CIRCLES, it.Transformation.INVERT, it.Transformation.NOISE],
    [it.Transformation.CIRCLES, it.Transformation.SHIFT_COLOR, it.Transformation.NOISE],
    [it.Transformation.INVERT, it.Transformation.SHIFT_COLOR, it.Transformation.NOISE],
]